// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BrowseGameLog() {
  return window['go']['main']['App']['BrowseGameLog']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectToSCBridge() {
  return window['go']['main']['App']['ConnectToSCBridge']();
}

export function DisconnectFromSCBridge() {
  return window['go']['main']['App']['DisconnectFromSCBridge']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetEventCategories() {
  return window['go']['main']['App']['GetEventCategories']();
}

export function GetEventCounts() {
  return window['go']['main']['App']['GetEventCounts']();
}

export function GetEventLogPath() {
  return window['go']['main']['App']['GetEventLogPath']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetFriendsDelta(arg1) {
  return window['go']['main']['App']['GetFriendsDelta'](arg1);
}

export function GetMinimizeToTray() {
  return window['go']['main']['App']['GetMinimizeToTray']();
}

export function GetRecentEvents() {
  return window['go']['main']['App']['GetRecentEvents']();
}

export function GetStartWithWindows() {
  return window['go']['main']['App']['GetStartWithWindows']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSyncPreferences() {
  return window['go']['main']['App']['GetSyncPreferences']();
}

export function GetTotalEvents() {
  return window['go']['main']['App']['GetTotalEvents']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenDownloadURL(arg1) {
  return window['go']['main']['App']['OpenDownloadURL'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function ResetSyncPreferences() {
  return window['go']['main']['App']['ResetSyncPreferences']();
}

export function SetEnvironment(arg1) {
  return window['go']['main']['App']['SetEnvironment'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetStartWithWindows(arg1) {
  return window['go']['main']['App']['SetStartWithWindows'](arg1);
}

export function SetSyncPreference(arg1, arg2) {
  return window['go']['main']['App']['SetSyncPreference'](arg1, arg2);
}
