// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {events} from '../models';

export function ApplyUpdate(arg1:string):Promise<string>;

export function BrowseGameLog():Promise<string>;

export function CheckForUpdate():Promise<updater.ReleaseInfo>;

export function ConnectToSCBridge():Promise<main.ConnectionStatus>;

export function DisconnectFromSCBridge():Promise<void>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetDataDir():Promise<string>;

export function GetDatabasePath():Promise<string>;

export function GetEnvironment():Promise<string>;

export function GetEventCategories():Promise<Array<events.EventCategory>>;

export function GetEventCounts():Promise<Record<string, number>>;

export function GetEventLogPath():Promise<string>;

export function GetFriends():Promise<Array<main.FriendEntry>>;

export function GetFriendsDelta(arg1:string):Promise<Array<main.FriendEntry>>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetRecentEvents():Promise<Array<main.EventEntry>>;

export function GetStartWithWindows():Promise<boolean>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSyncPreferences():Promise<Record<string, boolean>>;

export function GetTotalEvents():Promise<number>;

export function GetVersion():Promise<string>;

export function OpenDownloadURL(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function ResetSyncPreferences():Promise<Record<string, boolean>>;

export function SetEnvironment(arg1:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetStartWithWindows(arg1:boolean):Promise<void>;

export function SetSyncPreference(arg1:string,arg2:boolean):Promise<void>;
